I made some minor quality of life improvements
b5i/YouTubeKit pull request #17
Opened 2024-01-28 06:54 UTC by Mcrich23

Hello,
A couple days ago I forked YoutubeKit and made some adjustments that I thought I would share. So far I have:
- Made more components codable (helpful for storing video information locally)
  - `HeaderTypes`
  - `MoreVideoInfosResponse`
    - `AuthenticatedData`
    - `LikeStatus`
    - `YouTubeDescriptionPart`
      - `YouTubeDescriptionPartRole`
      - `YouTubeDescriptionPartStyle`
    - `Chapter`
- Made some components hashable to allow for easy iteration
  - `YTPrivacy`
  - `YTLittleChannelInfos`
  - `YTThumbnail`
  - `YTSearchResult`
  - `YTSearchResultType`
- Added handle support to `YTChannel` and `ChannelInfosResponse`
- Made channels in `YTVideo` more reliable

2024-02-07 15:31 UTC, b5i requested changes

2024-02-07 15:32 UTC, Mcrich23 commented on Sources/YouTubeKit/YouTubeResponseTypes/ChannelInfos/ChannelInfosResponse.swift
>      public var publicIdentifier: String?
Ok thank you. I think public identifier is misleading, maybe handle would be better in general.

2024-02-07 15:39 UTC, b5i commented on Sources/YouTubeKit/YouTubeResponseTypes/ChannelInfos/ChannelInfosResponse.swift
>      public var publicIdentifier: String?
You can rename publicIdentifier to handle

2024-02-12 11:19 UTC, Mcrich23 commented
there are also some critical fixes in here. I suggest a merge asap

2024-02-12 15:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/b5i/YouTubeKit?pullRequest=17) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/b5i/YouTubeKit?pullRequest=17) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/b5i/YouTubeKit?pullRequest=17) it.</sub>

2024-02-14 09:16 UTC, b5i requested changes

2024-02-14 09:16 UTC, b5i commented on Sources/YouTubeKit/YouTubeResponseTypes/PlaylistInfos/PlaylistInfosResponse.swift
> +        let playlistVideoListRendererJSON = json["contents"]["twoColumnBrowseResultsRenderer"]["tabs"].array?[0]["tabRenderer"]["content"]["sectionListRenderer"]["contents"].array?[0]["itemSectionRen
Please remove that line, it's unused

2024-02-14 09:16 UTC, b5i commented on Sources/YouTubeKit/YouTubeResponseTypes/PlaylistInfos/PlaylistInfosResponse.swift
> +                    guard let finalVideoArray = thirdVideoArrayPart["playlistVideoListRenderer"]["contents"].array else { continue }
Please put that line before before we declare `secondHeader`.

2024-02-14 09:16 UTC, b5i commented on Sources/YouTubeKit/YouTubeResponseTypes/ChannelInfos/ChannelInfosResponse.swift
> +            toReturn.handle = channelInfos["channelHandleText"]["runs"].array?.first?["text"].string
You can just write `toReturn.handle = handle` as you declare it the line above.

2024-02-14 20:30 UTC, Mcrich23 commented on Sources/YouTubeKit/YouTubeResponseTypes/PlaylistInfos/PlaylistInfosResponse.swift
> +                    guard let finalVideoArray = thirdVideoArrayPart["playlistVideoListRenderer"]["contents"].array else { continue }
why? the stuff above is not related to `finalVideoArray` and should be set regardless of the status of `finalVideoArray`

2024-02-14 20:31 UTC, Mcrich23 commented on Sources/YouTubeKit/YouTubeResponseTypes/ChannelInfos/ChannelInfosResponse.swift
> +            toReturn.handle = channelInfos["channelHandleText"]["runs"].array?.first?["text"].string
Shouldn't it return nil if handle is empty?

2024-02-14 21:19 UTC, b5i commented on Sources/YouTubeKit/YouTubeResponseTypes/ChannelInfos/ChannelInfosResponse.swift
> +            toReturn.handle = channelInfos["channelHandleText"]["runs"].array?.first?["text"].string
`let handle = channelInfos["channelHandleText"]["runs"].array?.first?["text"].string` is a boolean + the definition of the variable handle that is a non-optional string so it can't be nil otherwise it would pass to the next conditional block.

2024-02-14 21:21 UTC, b5i commented on Sources/YouTubeKit/YouTubeResponseTypes/PlaylistInfos/PlaylistInfosResponse.swift
> +                    guard let finalVideoArray = thirdVideoArrayPart["playlistVideoListRenderer"]["contents"].array else { continue }
If the part does not contain this `finalVideoArray ` it means there's a chance that this item is something else than what we want so it's better to directly `continue` at the beginning so you avoid having eventual "fake" values for the `toReturn.userInteractions` properties.

2024-02-14 22:27 UTC, Mcrich23 commented on Sources/YouTubeKit/YouTubeResponseTypes/ChannelInfos/ChannelInfosResponse.swift
> +            toReturn.handle = channelInfos["channelHandleText"]["runs"].array?.first?["text"].string
`let handle = channelInfos["channelHandleText"]["runs"].array?.first?["text"].string` is not a boolean

2024-02-14 22:28 UTC, Mcrich23 commented on Sources/YouTubeKit/YouTubeResponseTypes/PlaylistInfos/PlaylistInfosResponse.swift
> +                    guard let finalVideoArray = thirdVideoArrayPart["playlistVideoListRenderer"]["contents"].array else { continue }
ok, I will change this

2024-02-14 22:35 UTC, b5i commented on Sources/YouTubeKit/YouTubeResponseTypes/ChannelInfos/ChannelInfosResponse.swift
> +            toReturn.handle = channelInfos["channelHandleText"]["runs"].array?.first?["text"].string
> `let handle = channelInfos["channelHandleText"]["runs"].array?.first?["text"].string` is not a boolean

I probably misexplained myself but what you do with the if let is an optional binding that will have kind of the same role as a boolean in the if statement.

2024-02-15 06:01 UTC, Mcrich23 commented on Sources/YouTubeKit/YouTubeResponseTypes/ChannelInfos/ChannelInfosResponse.swift
> +            toReturn.handle = channelInfos["channelHandleText"]["runs"].array?.first?["text"].string
ahh, I see the mistake now. Should be fixed

2024-02-15 20:10 UTC, b5i approved these changes

2024-02-15 20:11 UTC, b5i commented
Thanks!

2024-02-15 20:11 UTC, merged